### ISSUE TITLE
Understanding the Data output of the IMD69F130 2GO

### ISSUE THREAD

**Issue by MTE-Iot** [Infineon/i2s-microphone#1]
Hi,

I am using the im69df130 shield2go in combination with the raspberry 3, like it is recommend in your tutorial. I followed the tutorial step by step and i get some data from the sensor. so far so good. But i have quite my problems making sense out of the data to make sure the sensor is working properly. If i play the recorded audio file it is just noise, even if i play a test signal of 200 Hz. 
For a better understanding of the data i wrote the wav file to a text file and the Values oscillate between -1 and 1. For my understanding that is normal for a pdm microphone? (Excuse me for that question i am not an expert on that topic).
I want to use the sensor for a soundpressure level measurement, like it is done her: https://github.com/Infineon/IM69D130-Microphone-Shield2Go/tree/master/examples/soundPressureLevel
would it be possible to calculate the SPL the same way it is done in the Arduino code just in python?

If you could help me with understanding the data that i get from the sensor that would be a big relief or if you can show me if there are documents about it.

thanks in advance

**Comment by pandayswarnam** [comment]
hi @MTE-Iot,
The first issue regarding the noise.
Noise in the recording is majorly because of loose connections.
Visit this [link](https://github.com/Infineon/GetStarted_IM69D130_With_RaspberryPi/wiki) for more info.
For correct installation check for the option of a sound card in that, you can easily see whether the i2s port is getting identified as an input microphone or not.

There are no documents existing at the application level for SPL but yes that can be achieved in raspberry pi.

**Comment by pandayswarnam** [comment]
HI,
Hope the issue is resolved, In case of any other query feel free to reopen the issue.

thanks 
Infineon team
